export type introContents = {
  title: string;
  description?: string;
  icon_name_01?: string;
  icon_name_02?: string;
  icon_name_03?: string;
  icon_name_04?: string;
  icon_name_05?: string;
  icon_description_01?: string;
  icon_description_02?: string;
  icon_description_03?: string;
  icon_description_04?: string;
  icon_description_05?: string;
  btn_img_01?: string;
  btn_img_02?: string;
  btn_img_03?: string;
  btn_img_04?: string;
  btn_img_05?: string;
  content_img_01?: string;
  content_img_02?: string;
  content_img_03?: string;
  content_img_04?: string;
  content_img_05?: string;
};
